// Centralized mock data for UI fallback during development

export const MOCK_USER = {
  id: 'usr_998124',
  name: 'Alex Rivera',
  email: 'alex@devcorp.io',
  role: 'Infrastructure Lead',
  apiKey: 'hk_live_9a8b7c6d5e4f3a2b1c0d',
};

export const MOCK_ENDPOINTS = [
  {
    id: 'ep_rzp_prod',
    name: 'Razorpay Billing Gateway',
    provider: 'Razorpay',
    targetUrl: 'https://api.devcorp.io/webhooks/razorpay',
    webhookSecret: 'whsec_rzp_99482710384756291',
    hooklensUrl: 'https://api.hooklens.dev/wh/ep_rzp_prod',
    status: 'ACTIVE',
    totalEvents: 14820,
    successRate: 98.4,
    avgLatency: 142,
    createdAt: '2026-01-15T08:30:00Z',
  },
  {
    id: 'ep_stripe_prod',
    name: 'Stripe Subscriptions',
    provider: 'Stripe',
    targetUrl: 'https://api.devcorp.io/webhooks/stripe',
    webhookSecret: 'whsec_str_10492817264859182',
    hooklensUrl: 'https://api.hooklens.dev/wh/ep_stripe_prod',
    status: 'ACTIVE',
    totalEvents: 42100,
    successRate: 99.9,
    avgLatency: 98,
    createdAt: '2026-01-10T11:20:00Z',
  },
  {
    id: 'ep_wa_notify',
    name: 'WhatsApp Customer Alerts',
    provider: 'WhatsApp',
    targetUrl: 'https://notify.devcorp.io/v1/whatsapp',
    webhookSecret: 'whsec_wa_8837192049182746',
    hooklensUrl: 'https://api.hooklens.dev/wh/ep_wa_notify',
    status: 'DEGRADED',
    totalEvents: 8900,
    successRate: 84.2,
    avgLatency: 1060,
    createdAt: '2026-02-01T14:15:00Z',
  },
  {
    id: 'ep_custom_auth',
    name: 'Internal SSO Sync',
    provider: 'Custom',
    targetUrl: 'https://auth.devcorp.io/hooks/sync',
    webhookSecret: 'whsec_cst_7749102837495018',
    hooklensUrl: 'https://api.hooklens.dev/wh/ep_custom_auth',
    status: 'ACTIVE',
    totalEvents: 3400,
    successRate: 99.1,
    avgLatency: 120,
    createdAt: '2026-02-10T09:00:00Z',
  },
];

export const MOCK_EVENTS = [
  {
    id: 'evt_991823',
    endpointId: 'ep_rzp_prod',
    endpointName: 'Razorpay Billing Gateway',
    provider: 'Razorpay',
    eventType: 'payment.captured',
    status: 'FAILED',
    httpStatus: 503,
    attempts: 3,
    maxAttempts: 5,
    latency: 1060,
    receivedAt: '2026-08-21T13:45:12Z',
    payloadSize: 1420,
    payloadHash: 'sha256:8f912a73b4e...',
    ipAddress: '52.66.12.184',
    payload: {
      entity: 'event',
      account_id: 'acc_H8192JSK',
      event: 'payment.captured',
      contains: ['payment'],
      payload: {
        payment: {
          entity: {
            id: 'pay_L9812JSD921',
            amount: 499900,
            currency: 'INR',
            status: 'captured',
            order_id: 'order_M1092KJS',
            method: 'card',
            email: 'customer@acme.com',
            contact: '+919876543210',
          },
        },
      },
      created_at: 1771681512,
    },
    headers: {
      'host': 'api.hooklens.dev',
      'user-agent': 'Razorpay-Webhook/v2',
      'content-type': 'application/json',
      'x-razorpay-signature': '4a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b',
      'x-forwarded-for': '52.66.12.184',
    },
    aiDiagnosis: {
      summary: 'Target API returned HTTP 503 Service Unavailable on 2 consecutive attempts and timed out on the third.',
      confidence: '96%',
      evidence: [
        '3 consecutive failures observed',
        'Latency increased significantly from 240ms to 2.8s',
        'DNS resolution & TCP handshake succeeded',
        'Target web server sent 503 headers with Retry-After',
      ],
      recommendation: 'Check target API database connection pool health and click Replay Webhook once backend recovers.',
    },
  },
  {
    id: 'evt_991822',
    endpointId: 'ep_stripe_prod',
    endpointName: 'Stripe Subscriptions',
    provider: 'Stripe',
    eventType: 'customer.subscription.updated',
    status: 'SUCCESS',
    httpStatus: 200,
    attempts: 1,
    maxAttempts: 5,
    latency: 142,
    receivedAt: '2026-08-21T13:42:00Z',
    payloadSize: 2840,
    payloadHash: 'sha256:1a2b3c4d5e...',
    ipAddress: '54.187.205.235',
    payload: {
      id: 'evt_1M092JS817263',
      object: 'event',
      type: 'customer.subscription.updated',
      data: {
        object: {
          id: 'sub_1M092JS817263',
          customer: 'cus_991823719',
          status: 'active',
          current_period_end: 1774273200,
        },
      },
    },
    headers: {
      'user-agent': 'Stripe/1.0 (+https://stripe.com/docs/webhooks)',
      'stripe-signature': 't=1771681320,v1=9a8b7c6d5e4f3a2b1c0d',
    },
  },
  {
    id: 'evt_991821',
    endpointId: 'ep_wa_notify',
    endpointName: 'WhatsApp Customer Alerts',
    provider: 'WhatsApp',
    eventType: 'message.delivered',
    status: 'RETRYING',
    httpStatus: 500,
    attempts: 2,
    maxAttempts: 5,
    latency: 850,
    receivedAt: '2026-08-21T13:40:10Z',
    payloadSize: 980,
    payloadHash: 'sha256:7c8b9a0f...',
    ipAddress: '31.13.71.1',
    payload: {
      object: 'whatsapp_business_account',
      entry: [{ id: '1092817263', changes: [{ value: { messaging_product: 'whatsapp', status: 'delivered' } }] }],
    },
    headers: {
      'user-agent': 'FacebookExternalHit/1.1',
      'x-hub-signature-256': 'sha256=182736452910',
    },
    aiDiagnosis: {
      summary: 'Target server thrown an unhandled NullPointerException during payload deserialization.',
      confidence: '91%',
      evidence: ['Internal Server Error 500 returned', 'Response body contained Java stack trace snippet'],
      recommendation: 'Fix null check on optional phone metadata field in consumer service.',
    },
  },
  {
    id: 'evt_991820',
    endpointId: 'ep_rzp_prod',
    endpointName: 'Razorpay Billing Gateway',
    provider: 'Razorpay',
    eventType: 'refund.processed',
    status: 'SUCCESS',
    httpStatus: 200,
    attempts: 1,
    maxAttempts: 5,
    latency: 188,
    receivedAt: '2026-08-21T13:35:04Z',
    payloadSize: 1150,
    payloadHash: 'sha256:3d2e1f0a...',
    ipAddress: '52.66.12.184',
    payload: { entity: 'event', event: 'refund.processed', payload: { refund: { id: 'rfnd_991827' } } },
    headers: { 'user-agent': 'Razorpay-Webhook/v2' },
  },
  {
    id: 'evt_991819',
    endpointId: 'ep_wa_notify',
    endpointName: 'WhatsApp Customer Alerts',
    provider: 'WhatsApp',
    eventType: 'message.failed',
    status: 'DEAD_LETTERED',
    httpStatus: 404,
    attempts: 5,
    maxAttempts: 5,
    latency: 310,
    receivedAt: '2026-08-21T13:20:00Z',
    payloadSize: 890,
    payloadHash: 'sha256:5e4d3c2b...',
    ipAddress: '31.13.71.1',
    payload: { event: 'message.failed', error: 'User opted out' },
    headers: { 'user-agent': 'FacebookExternalHit/1.1' },
    aiDiagnosis: {
      summary: 'Endpoint URL path route `/v1/whatsapp` returned 404 Not Found consistently across all 5 retries.',
      confidence: '99%',
      evidence: ['5 consecutive 404 errors', 'Target route was unmapped in release v2.4.1'],
      recommendation: 'Verify target route mapping in application router or update Endpoint target URL.',
    },
  },
  {
    id: 'evt_991818',
    endpointId: 'ep_custom_auth',
    endpointName: 'Internal SSO Sync',
    provider: 'Custom',
    eventType: 'user.provisioned',
    status: 'QUEUED',
    httpStatus: null,
    attempts: 0,
    maxAttempts: 5,
    latency: null,
    receivedAt: '2026-08-21T13:50:00Z',
    payloadSize: 640,
    payloadHash: 'sha256:9f8e7d6c...',
    ipAddress: '10.0.4.12',
    payload: { user_id: 'usr_881927', email: 'sam@devcorp.io', action: 'provision' },
    headers: { 'content-type': 'application/json' },
  },
];

export const MOCK_ATTEMPTS = [
  {
    attemptNumber: 1,
    type: 'AUTOMATIC',
    status: 'FAILED',
    httpStatus: 503,
    latency: 1200,
    timestamp: '2026-08-21T13:45:13Z',
    error: 'HTTP 503 Service Unavailable',
    requestHeaders: { 'content-type': 'application/json', 'x-hooklens-delivery-id': 'del_1001' },
    responseHeaders: { 'server': 'nginx/1.18.0', 'retry-after': '30' },
    responseBody: '{"error": "Database connection pool exhausted"}',
  },
  {
    attemptNumber: 2,
    type: 'AUTOMATIC',
    status: 'FAILED',
    httpStatus: 503,
    latency: 2800,
    timestamp: '2026-08-21T13:45:45Z',
    error: 'HTTP 503 Service Unavailable',
    requestHeaders: { 'content-type': 'application/json', 'x-hooklens-delivery-id': 'del_1002' },
    responseHeaders: { 'server': 'nginx/1.18.0' },
    responseBody: '{"error": "Database connection pool exhausted"}',
  },
  {
    attemptNumber: 3,
    type: 'AUTOMATIC',
    status: 'FAILED',
    httpStatus: 504,
    latency: 10000,
    timestamp: '2026-08-21T13:47:15Z',
    error: 'ETIMEDOUT Gateway Timeout after 10000ms',
    requestHeaders: { 'content-type': 'application/json', 'x-hooklens-delivery-id': 'del_1003' },
    responseHeaders: {},
    responseBody: 'Gateway Timeout',
  },
];

export const MOCK_REPLAYS = [
  {
    replayId: 'rpl_991024',
    eventId: 'evt_991823',
    endpointName: 'Razorpay Billing Gateway',
    eventType: 'payment.captured',
    triggeredBy: 'Alex Rivera (alex@devcorp.io)',
    status: 'SUCCESS',
    httpStatus: 200,
    latency: 210,
    timestamp: '2026-08-21T13:48:30Z',
  },
  {
    replayId: 'rpl_991023',
    eventId: 'evt_991819',
    endpointName: 'WhatsApp Customer Alerts',
    eventType: 'message.failed',
    triggeredBy: 'Automated DLQ Recovery Script',
    status: 'FAILED',
    httpStatus: 404,
    latency: 145,
    timestamp: '2026-08-21T12:10:00Z',
  },
];

export const MOCK_SECURITY_STATS = {
  hmacVerified: 68420,
  freshnessProtected: 1204,
  replayProtected: 412,
  ssrfBlocked: 89,
  piiRedacted: 14200,
  recentSecurityEvents: [
    {
      id: 'sec_1092',
      type: 'INVALID_SIGNATURE',
      severity: 'HIGH',
      provider: 'Stripe',
      endpoint: 'Stripe Subscriptions',
      ip: '185.220.101.4',
      details: 'HMAC signature mismatch on webhook header `stripe-signature`. Request rejected.',
      timestamp: '2026-08-21T13:14:00Z',
    },
    {
      id: 'sec_1091',
      type: 'SSRF_BLOCKED',
      severity: 'CRITICAL',
      provider: 'Custom',
      endpoint: 'Internal SSO Sync',
      ip: '10.0.4.12',
      details: 'Attempted to target private RFC1918 address `http://169.254.169.254/latest/meta-data/`. Egress Guard blocked.',
      timestamp: '2026-08-21T12:55:00Z',
    },
    {
      id: 'sec_1090',
      type: 'REPLAY_ATTEMPT',
      severity: 'MEDIUM',
      provider: 'Razorpay',
      endpoint: 'Razorpay Billing Gateway',
      ip: '52.66.12.184',
      details: 'Duplicate webhook payload ID detected within 300s window. Idempotency layer deduplicated.',
      timestamp: '2026-08-21T11:40:00Z',
    },
  ],
};

export const MOCK_VOLUME_SERIES = [
  { time: '00:00', volume: 1200, success: 1180, failed: 20 },
  { time: '04:00', volume: 800, success: 790, failed: 10 },
  { time: '08:00', volume: 3400, success: 3350, failed: 50 },
  { time: '12:00', volume: 6200, success: 6020, failed: 180 },
  { time: '16:00', volume: 5100, success: 5010, failed: 90 },
  { time: '20:00', volume: 2900, success: 2880, failed: 20 },
];
